version: "3.5"

services:
  pulsar:
    image: apachepulsar/pulsar:latest
    container_name: pulsar
    command: bin/pulsar standalone
    ports:
      - "6650:6650"
      - "8080:8080"
    environment:
      PULSAR_MEM: "-Xms512m -Xmx512m -XX:MaxDirectMemorySize=1g"

  pulsar-manager:
    image: apachepulsar/pulsar-manager:v0.2.0
    container_name: pulsar-manager
    ports:
      - "9527:9527"
      - "7750:7750"
    depends_on:
      - pulsar
    environment:
      SPRING_CONFIGURATION_FILE: /pulsar-manager/pulsar-manager/application.properties
    volumes:
      - ./init-admin.sh:/init-admin.sh:ro
    command: sh -c "/init-admin.sh && /pulsar-manager/bin/pulsar-manager"

  pulsar-rest-proxy:
    image: apachepulsar/pulsar:latest
    container_name: pulsar-rest-proxy
    command: bin/pulsar proxy
    ports:
      - "8081:8080"
    depends_on:
      - pulsar
    environment:
      PULSAR_PROXY_SERVICE_URL: pulsar://pulsar:6650
      PULSAR_PROXY_WEB_SERVICE_URL: http://pulsar:8080
